env:
    es2023: true
    node: true
extends:
    - eslint:recommended
    - prettier
    - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: latest
    sourceType: module
plugins:
    - '@typescript-eslint'
    - 'prettier'
    - 'import'
rules:
    import/extensions:
        - error
        - js: never
        - jsx: never
        - ts: never
        - tsx: never
    no-restricted-globals:
        - error
        - window
    indent:
        - error
        - 4
    linebreak-style:
        - error
        - windows
    quotes:
        - error
        - single
    semi:
        - error
        - always
    settings:
        - import/parsers:
              - .ts
              - .tsx
        - import/resolver:
              - node: true
              - eslint-import-resolver-typescript: true
